/**
 * Production Data Fixtures
 *
 * Test fixtures matching the production JSON data shape from the reference schema.
 * These fixtures are used across all test suites for consistent test data.
 */

export const FIXTURES = {
  companies: {
    flextr: {
      id: 'cmp_flextr_4241',
      displayId: 'FLX-4241',
      displayName: 'Flextr Technologies',
      legalName: 'Flextr Technologies Pvt Ltd',
      email: 'admin@flextr.com',
      phone: '+91-9876543210',
      website: 'https://flextr.com',
      industry: 'Technology',
      companySize: '50-200',
      status: 'active' as const,
      employeeCount: 47,
      address: {
        street: '123 Tech Park',
        city: 'Bangalore',
        state: 'Karnataka',
        zipCode: '560001',
        country: 'India',
      },
      configuration: {
        timezone: 'Asia/Kolkata',
        currency: 'INR',
        dateFormat: 'DD/MM/YYYY',
        language: 'en',
      },
      primaryAdmin: {
        name: 'Rahul Sharma',
        email: 'rahul@flextr.com',
        phone: '+91-9876543210',
        userId: 'uid_flextr_admin_01',
        membershipId: 'mbr_flextr_4241_4825',
      },
      subscription: {
        planId: 'plan_growth_monthly',
        planName: 'Growth Plan',
        status: 'active' as const,
        startDate: 1695254400000,
        endDate: 1727395200000,
      },
      createdAt: 1690848000000,
      updatedAt: 1695859200000,
    },
    naukrigram: {
      id: 'cmp_naukrigram_3984',
      displayId: 'NKG-3984',
      displayName: 'NaukriGram Services',
      legalName: 'NaukriGram Services LLP',
      email: 'hr@naukrigram.com',
      phone: '+91-9123456789',
      website: 'https://naukrigram.com',
      industry: 'HR Services',
      companySize: '10-50',
      status: 'active' as const,
      employeeCount: 23,
      address: {
        street: '456 Business Hub',
        city: 'Mumbai',
        state: 'Maharashtra',
        zipCode: '400001',
        country: 'India',
      },
      configuration: {
        timezone: 'Asia/Kolkata',
        currency: 'INR',
        dateFormat: 'DD/MM/YYYY',
        language: 'en',
      },
      primaryAdmin: {
        name: 'Priya Patel',
        email: 'priya@naukrigram.com',
        userId: 'uid_nkg_admin_01',
        membershipId: 'mbr_naukrigram_3984_9365',
      },
      subscription: {
        planId: 'plan_starter_monthly',
        planName: 'Starter Plan',
        status: 'trial' as const,
        startDate: 1695254400000,
        endDate: 1697932800000,
        trialEndDate: 1697932800000,
      },
      createdAt: 1693526400000,
      updatedAt: 1695859200000,
    },
  },

  memberships: {
    flextrOwner: {
      id: 'mbr_flextr_4241_4825',
      userId: 'uid_flextr_admin_01',
      companyId: 'cmp_flextr_4241',
      companyDisplayId: 'FLX-4241',
      companyName: 'Flextr Technologies',
      email: 'rahul@flextr.com',
      name: 'Rahul Sharma',
      phone: '+91-9876543210',
      role: 'company_owner' as const,
      accountStatus: 'active' as const,
      invitationStatus: 'accepted' as const,
      invitationAcceptedAt: '2023-09-20T10:30:00.000Z',
      isPrimary: true,
      createdAt: 1690848000000,
      updatedAt: 1695859200000,
    },
    naukrigramOwner: {
      id: 'mbr_naukrigram_3984_9365',
      userId: 'uid_nkg_admin_01',
      companyId: 'cmp_naukrigram_3984',
      companyDisplayId: 'NKG-3984',
      companyName: 'NaukriGram Services',
      email: 'priya@naukrigram.com',
      name: 'Priya Patel',
      role: 'company_owner' as const,
      accountStatus: 'active' as const,
      invitationStatus: 'accepted' as const,
      invitationAcceptedAt: '2023-09-01T08:00:00.000Z',
      isPrimary: true,
      createdAt: 1693526400000,
      updatedAt: 1695859200000,
    },
    naukrigramHrAdmin: {
      id: 'mbr_naukrigram_3984_9447',
      userId: 'uid_nkg_hr_01',
      companyId: 'cmp_naukrigram_3984',
      companyDisplayId: 'NKG-3984',
      companyName: 'NaukriGram Services',
      email: 'hr.admin@naukrigram.com',
      name: 'Anjali Kumar',
      role: 'hr_admin' as const,
      accountStatus: 'active' as const,
      invitationStatus: 'accepted' as const,
      invitationAcceptedAt: '2023-09-05T14:00:00.000Z',
      isPrimary: false,
      createdAt: 1693785600000,
      updatedAt: 1695859200000,
    },
    disabledMembership: {
      id: 'mbr_disabled_test',
      userId: 'uid_disabled_user',
      companyId: 'cmp_flextr_4241',
      companyDisplayId: 'FLX-4241',
      companyName: 'Flextr Technologies',
      email: 'disabled@flextr.com',
      name: 'Disabled User',
      role: 'hr_admin' as const,
      accountStatus: 'disabled' as const,
      invitationStatus: 'accepted' as const,
      isPrimary: false,
      createdAt: 1690848000000,
      updatedAt: 1695859200000,
    },
    suspendedMembership: {
      id: 'mbr_suspended_test',
      userId: 'uid_suspended_user',
      companyId: 'cmp_flextr_4241',
      companyDisplayId: 'FLX-4241',
      companyName: 'Flextr Technologies',
      email: 'suspended@flextr.com',
      name: 'Suspended User',
      role: 'hr_admin' as const,
      accountStatus: 'suspended' as const,
      invitationStatus: 'accepted' as const,
      isPrimary: false,
      createdAt: 1690848000000,
      updatedAt: 1695859200000,
    },
    pendingInvitation: {
      id: 'mbr_pending_test',
      userId: '',
      companyId: 'cmp_flextr_4241',
      companyDisplayId: 'FLX-4241',
      companyName: 'Flextr Technologies',
      email: 'pending@flextr.com',
      name: 'Pending User',
      role: 'hr_admin' as const,
      accountStatus: 'inactive' as const,
      invitationStatus: 'pending' as const,
      isPrimary: false,
      createdAt: 1690848000000,
      updatedAt: 1695859200000,
    },
  },

  employees: {
    active: {
      id: 'emp_001',
      firstName: 'Rajesh',
      lastName: 'Kumar',
      email: 'rajesh@flextr.com',
      phone: '+91-9876500001',
      department: 'Engineering',
      departmentId: 'dept_eng_001',
      designation: 'Senior Developer',
      jobTitle: 'Senior Developer',
      location: 'Bangalore HQ',
      locationId: 'loc_blr_001',
      employmentType: 'full_time' as const,
      status: 'active' as const,
      salary: 1200000,
      dateOfJoining: 1640995200000,
      gender: 'male',
      createdAt: 1640995200000,
      updatedAt: 1695859200000,
    },
    onLeave: {
      id: 'emp_002',
      firstName: 'Meera',
      lastName: 'Singh',
      email: 'meera@flextr.com',
      department: 'Design',
      departmentId: 'dept_des_001',
      designation: 'Lead Designer',
      employmentType: 'full_time' as const,
      status: 'on_leave' as const,
      dateOfJoining: 1656633600000,
      createdAt: 1656633600000,
      updatedAt: 1695859200000,
    },
  },

  departments: {
    engineering: {
      id: 'dept_eng_001',
      name: 'Engineering',
      description: 'Software development and technical architecture',
      headName: 'Rajesh Kumar',
      headEmail: 'rajesh@flextr.com',
      employeeCount: 15,
      status: 'active' as const,
      createdAt: 1640995200000,
      updatedAt: 1695859200000,
    },
  },

  locations: {
    headquarters: {
      id: 'loc_blr_001',
      name: 'Bangalore HQ',
      type: 'headquarters' as const,
      address: {
        street: '123 Tech Park',
        city: 'Bangalore',
        state: 'Karnataka',
        zipCode: '560001',
        country: 'India',
      },
      phone: '+91-80-12345678',
      timezone: 'Asia/Kolkata',
      isHeadquarters: true,
      employeeCount: 35,
      status: 'active' as const,
      createdAt: 1640995200000,
      updatedAt: 1695859200000,
    },
  },

  plans: {
    starter: {
      id: 'plan_starter_monthly',
      name: 'Starter Plan',
      description: 'Basic HR management for small teams',
      price: 999,
      interval: 'monthly' as const,
      features: { employees: true, departments: true, locations: true, documents: false },
      limits: { maxEmployees: 25, maxAdmins: 2, maxDepartments: 5, maxLocations: 2, maxStorage: 500 },
      status: 'active' as const,
    },
    growth: {
      id: 'plan_growth_monthly',
      name: 'Growth Plan',
      description: 'Complete HR suite for growing businesses',
      price: 2999,
      interval: 'monthly' as const,
      features: { employees: true, departments: true, locations: true, documents: true },
      limits: { maxEmployees: 100, maxAdmins: 5, maxDepartments: 20, maxLocations: 10, maxStorage: 5000 },
      status: 'active' as const,
    },
  },
} as const;
